# Exercise 1
## Authors: E. Vercesi; A. Dei Rossi, S. Huber*, L. Scarciglia

This Notebook is a guideline for Exercise 1.

Exercises marked with a (*) are a bit more challenging.

## Lists
Lists are one of the fundamental data structures in Python. They are used to store ordered collections of items. 

Given the following list (of fruits), learn how to 
1. Access elements: print the first and last element (what is the index of the first element? What is index -1?).
2. Modify elements (e.g, change the third element "cherry" to "pineapple").
3. Get the length of the list.
4. Add one element ("blueberry") at the end.
5. Remove one element ("banana"). Take care of what functions [`pop`](https://www.w3schools.com/python/ref_list_pop.asp) or [`remove`](https://www.w3schools.com/python/ref_list_remove.asp) return and what happens to the original list. What is the meaning of *in-place* method?
6. Learn about the meaning of slicing, then slice your list (get all elements in between index 1 and 3 inclusive).
7. (*) Learn about the meaning of [list comprehension](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions) and filter your list of fruits by keeping only fruits starting with "a".

In [1]:
fruits = ["apple", "banana", "cherry", "orange", "avocado"]

## 1: print first and last element
print(fruits[0])
## 2: "cherry" -> "pineapple"
fruits[2] = "pineapple"
## 3: length
len(fruits)
## 4: add "blueberry" at the end
fruits.append("blueberry")
## 5: remove "banana"
fruits.remove("banana")
## 6: slicing: get elements between index 1 and 3 inclusive
print(fruits[1:4])
## 7: list comprehension: filter fruits that start with "a"
fruits_starting_with_a = [fruit for fruit in fruits if fruit.startswith('a')]
print(fruits_starting_with_a)

apple
['pineapple', 'orange', 'avocado']
['apple', 'avocado']


## Numpy
NumPy is a fundamental Python library for numerical and scientific computing. It provides support for working with large, multi-dimensional arrays and matrices, as well as a collection of mathematical functions to operate on these arrays efficiently. 
In this part, we will start learning some numpy basics. Before continuing, make sure you have numpy installed in your virtual environment. If not, install it using Conda or Pip by typing in your terminal `conda/pip install numpy`.

In [2]:
import numpy as np
np.random.seed(42)

Question: what is the seed? What is it used for? Solution: see [here](https://medium.com/@debanjana.bhattacharyya9818/numpy-random-seed-101-explained-2e96ee3fd90b).

For fun: why is the seed often set at [42](https://www.youtube.com/watch?v=aboZctrHfK8)? ;)

### Create numpy arrays

Create numpy arrays out of:
- list (And try to change the value of the element in position [1, 1] from 5 to 10)
- tuple
- (*) set

and print the shape and the `dtype` of the arrays. Do you notice anything unexpected? .

In [ ]:
## 1: list
my_list = [[1, 2, 3], [4, 5, 6]]
np_list = np.array(my_list)
np_list[1][1] = 10
print(np_list)

## 2: tuple
my_tuple = (1, 2, 3)
np_tuple = np.array(my_tuple)
print(np_tuple)

## 3: set
my_set = {1, 2, 3}
np.array(my_set)

[[ 1  2  3]
 [ 4 10  6]]
[1 2 3]
{1, 2, 3}


Check functions [`np.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange) and [`np.linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) and create vectors of size (3, 4) ([`np.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)) with values from 0 to 11 using both functions.  

In [18]:
# np.arange
vectors = np.arange(12).reshape(3,4)
# np.linspace
np.linspace(0, 11, num=12, dtype=np.int16).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int16)

### Slicing

Take the above array of dimension (3, 4), and access (see [slicing](https://numpy.org/doc/stable/user/basics.indexing.html)):
1) element in position [1,2].
2) the third row.
3) the third column.
4) the 2x2 sub-matrix ranging in between the second and third row and first and second column.

In [32]:
## 1: access element
print(vectors[1,2])
## 2: access row
print(vectors[2])
## 3: access column
print(vectors[..., 2])
## 4: sub-matrix
rows = np.array([1,2], dtype=np.intp)
columns = np.array([0,1], dtype=np.intp)
print(vectors[rows[:, np.newaxis], columns])

6
[ 8  9 10 11]
[ 2  6 10]
[[4 5]
 [8 9]]


### Random arrays
Create random multidimensional arrays and inspect their shape. Try different combinations of dimensions and different distributions (normal, uniform)

1) Create a random array of size 4 of [uniform](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html) floating point numbers in the interval [0, 1).
2) Create a random array of size (3, 2) of uniform floating point numbers in the interval [0, 5).
3) Create a random array of size (2, 1, 2) of integers in the interval [10, 20].
4) Create a random array of size 10 over the [normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html) distribution, mean 3 and std dev 2.

In [21]:
## 1: 
np.random.rand(4)
## 2: 
np.random.uniform(0,5,(3,2))
## 3:
np.random.randint(10,20, (2,1,2))
## 4:
rng = np.random.default_rng(seed=42)
rng.normal(loc=3, scale=2, size=10)

array([ 3.60943416,  0.92003179,  4.50090239,  4.88112943, -0.90207038,
        0.39564099,  3.25568081,  2.36751482,  2.96639768,  1.29391214])

### Copy arrays

Please have a look at [`np.copy`](https://numpy.org/doc/stable/reference/generated/numpy.copy.html). 
1) Create a vector $v$ of size 3, copy it to a new vector $w$, change one entry of vector $w$ and make sure that $v$ is not affected.
2) What if we wanted to change vector $v$ when changing the entries of $w$? 

In [25]:
## 1: Create vector v, copy it to w, change w and make sure v is unaltered.
v = np.array([1,2,3])
w = np.copy(v)
w[0] = 5
print(v[0] == 1)
## 2: Create vector v, copy it to w, change w and make sure v is altered as well.
v = np.array([1,2,3])
w = v
w[0] = 5
print(v[0] == 5)

True
True


### Element-wise functions and broadcasting

1) Given $v = [1, 2, 3], w = [4, 5, 6]$ compute $v - w$, that is, element-wise subtraction. 

2) What happens if $v = [1, 2]$? 

3) set $\lambda=3$ and perform $\lambda w$. Why can't you use as variable name the word "lambda"?
 
4) (*) And if $v = \begin{bmatrix} 4 & 7 & 6 \\ 5 & 8 & 9 \end{bmatrix}$ (shape (2, 3)) and you want to subtract $w$ to all the rows of $v$? (Read carefully [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)).

5) (*) And if $v = \begin{bmatrix} 4 & 5 \\ 7 & 8 \\ 6 & 9 \end{bmatrix}$ (shape (3, 2)) and you want to subtract $w$ to all the columns of $v$? (See [`np.newaxis`](https://stackoverflow.com/a/41267079), `np.vstack` or `.T` transpose operator).



In [8]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

## 1: Perform v - w using numpy arrays

## 2: v is smaller than w, what does v - w do?
v2 = np.array([1, 2])

## 3: Multiply all entries of w by lambda = 3.

## 4: v is higher dimensional, subtract w from all the rows of v.
v4 = np.array([[4, 7, 6], [5, 8, 9]])

## 5: v is higher dimensional, subtract w from all the columns of v.
v5 = np.array([[4, 5], [7, 8], [6, 9]])

### Max, min, sum, along different axis

1) Get the max value in the matrix $v = \begin{bmatrix} 1 & 5 & 3 \\ 3 & 4 & 7 \end{bmatrix}$.
2) (*) Get the max value in the matrix $v$ along the columns (see [axis](https://www.pythonpool.com/numpy-axis/)). Predict the shape of the result vector.
3) Get the max value in the matrix $v$ along the rows. Predict the shape of the result vector.
4) (*) Create a random array of shape (2, 3, 4) and get the min along axis 1. Predict the shape of the result and understand what is going on.



In [25]:
v = np.array([[1, 5, 3], [3, 4, 7]])

## 1: get max value.
print(v.max())
print(v.max().shape)
## 2: get max value along the columns.
print(v.max(axis=0))
## 3: get the max value along the rows.
print(v.max(axis=1))
print(v.max(axis=1).shape)
## 4: Create a random array of shape (2, 3, 4) and get the min along axis = 1. Predict the shape of the output matrix.
r = np.random.randint(0,20,(2,3,4))
print(r)
r_min = r.min(axis=1)
print(f"r shape: {r_min.shape}")
print(f"r matrix: \n{r_min}")
print("--------------------")
print(r.min(axis=(1,2)))

7
()
[3 5 7]
[5 7]
(2,)
[[[15  1 16 19]
  [11 17  2  0]
  [ 0 18 10  4]]

 [[11  2  0  0]
  [ 7  9 10 11]
  [12 11 13  1]]]
r shape: (2, 4)
r matrix: 
[[0 1 2 0]
 [7 2 0 0]]
--------------------
[0 0]


### The value of the axis tells us which dimension will be collapsed (aka removed).

In the case of shape (2,3,4),
- `min(axis=0)` -> (3,4) 
- `min(axis=1)` -> (2,4)
- `min(axis=2)` -> (2,3)
- `min(axis=(1,2))` -> (2,)

### [`np.matmul`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html), [`np.dot`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html), [`@`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) and `*`

Learn the difference between these operands. (Keep in mind that `np.dot` does not get used frequently for high dimensional vectors).

1. Take the dot product between two integer random vectors of size 3. Can you do it in multiple ways? In case you can, check that the result is the same.
2. Take the element-wise product (Hadamard product) between two integer random matrices of size (4, 2). Predict the shape of the result.
3. Take the dot product between an integer random matrix of size (3, 2) and an integer random vector of size (2). Predict the shape of the result. Can you do it in multiple ways? In case you can, check that the result is the same.
4. Take the dot product between an integer random matrix of size (4, 3) and another integer random matrix of size (3, 2). Predict the shape of the result. Can you do it in multiple ways? In case you can, check that the result is the same.
5. (*) (Optional, again `np.dot` is not frequently used for high dimensional vectors) see the difference between the `np.dot` and `np.matmul` of two integer random matrices of shape (2, 3, 3). Predict the shape of the two results. 


In [49]:
## 1: take dot product of 1 dimensional vectors.
a = np.random.randint(0,5,size=3)
b = np.random.randint(0,5,size=3)
print(f'a: {a} \t b: {b}' )
print('np.dot:', np.dot(a, b))
print('np.matmul:', np.matmul(a, b))
print('a @ b:', a @ b)
print('np.dot == np.matmul:', np.dot(a, b) == np.matmul(a, b))
print('np.dot == a @ b:', np.dot(a, b) == a @ b)
print('--------------------------------')
## 2: take the Hadamard product of two matrices.
a = np.random.randint(0,10,size=(4,2))
b = np.random.randint(11,20,size=(4,2))
print(f'a: {a} \nb: {b}')
print('a * b:\n', a * b)
print('shape:\n', (a * b).shape)
print('--------------------------------')
## 3: take dot product matrix-vector.
a = np.random.randint(0,5,size=(3,2))
b = np.random.randint(0,5,size=2)
print(f'a:\n{a} \nb: {b}' )
print('np.dot:', np.dot(a, b))
print('np.matmul:', np.matmul(a, b))
print('np.dot == np.matmul:', np.dot(a, b) == np.matmul(a, b))
print('--------------------------------')
## 4: take dot product matrix-matrix.
a = np.random.randint(0,5,size=(4,3))
b = np.random.randint(0,5,size=(3,2))
print(f'a:\n{a} \nb:\n {b}' )
print('np.dot:\n', np.dot(a, b))
print('np.matmul:\n', np.matmul(a, b))
print('np.dot == np.matmul:', np.dot(a, b) == np.matmul(a, b))
## 5: np.dot vs np.matmul. 
a = np.random.randint(0,5,size=(2,3,3))
b = np.random.randint(0,5,size=(2,3,3))
print(f'a:\n{a} \nb:\n {b}' )
print('np.dot:\n', np.dot(a, b))
print('np.matmul:\n', np.matmul(a, b))
print('np.dot.shape:' , np.dot(a, b).shape, 'np.matmul.shape:', np.matmul(a, b).shape)

a: [2 3 3] 	 b: [4 4 1]
np.dot: 23
np.matmul: 23
a @ b: 23
np.dot == np.matmul: True
np.dot == a @ b: True
--------------------------------
a: [[6 9]
 [6 0]
 [6 4]
 [2 2]] 
b: [[14 12]
 [12 11]
 [15 14]
 [12 13]]
a * b:
 [[ 84 108]
 [ 72   0]
 [ 90  56]
 [ 24  26]]
shape:
 (4, 2)
--------------------------------
a:
[[3 3]
 [4 4]
 [0 1]] 
b: [4 3]
np.dot: [21 28  3]
np.matmul: [21 28  3]
np.dot == np.matmul: [ True  True  True]
--------------------------------
a:
[[2 3 1]
 [3 0 1]
 [2 0 1]
 [2 0 0]] 
b:
 [[1 4]
 [0 0]
 [2 3]]
np.dot:
 [[ 4 11]
 [ 5 15]
 [ 4 11]
 [ 2  8]]
np.matmul:
 [[ 4 11]
 [ 5 15]
 [ 4 11]
 [ 2  8]]
np.dot == np.matmul: [[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
a:
[[[1 1 4]
  [4 1 4]
  [2 1 4]]

 [[1 3 0]
  [1 0 4]
  [0 1 3]]] 
b:
 [[[4 1 4]
  [2 0 2]
  [1 3 4]]

 [[0 4 1]
  [4 0 1]
  [4 3 1]]]
np.dot:
 [[[[10 13 22]
   [20 16  6]]

  [[22 16 34]
   [20 28  9]]

  [[14 14 26]
   [20 20  7]]]


 [[[10  1 10]
   [12  4  4]]

  [[ 8 13 20]
   [16 16  

### Apply functions to vectors

Define a simple python function that computes $f(x,y) = xy + x + y$ for integer $x,y\in\mathbb{Z}$. 
Use numpy to apply such a function to two vectors of size 3, element by element. 

e.g. $v = [1,2,3]$, $w=[0,3,4]$, $f(v,w) = [1, 11, 19]$

Hint: see [`np.vectorize`](https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html)

In [50]:
## Define function f
def f(x: int, y: int) -> int:
    return x*y + x + y

vf = np.vectorize(f)
## Apply function f to vectors v, w element by element
v = np.array([1,2,3])
w = np.array([0,3,4])
print(vf(v, w))

[ 1 11 19]


### Filtering

Create a random vector of integers in the interval [0, 10) of size 10, and filter all elements larger than 4 and less than 8 and set them to 20. Try to do it using both [boolean masks](https://www.programiz.com/python-programming/numpy/boolean-indexing) and [`np.where`](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [61]:
## Filter elements in the interval [5, 8) and set them to 20
x = np.random.uniform(0,10,10)
condition = (x > 4) & (x < 8)
## 1: boolean masks.
print('before:', x)
y = x.copy()
y[condition] = 20
print('after:', y)
## 2: np.where.
x = np.where(condition, 20, x)
print('after where:', x)

before: [0.88543411 0.37596773 4.79781327 5.80757207 2.71686971 3.98287384
 0.91699335 3.36370464 5.22519192 7.32271807]
after: [ 0.88543411  0.37596773 20.         20.          2.71686971  3.98287384
  0.91699335  3.36370464 20.         20.        ]
after where: [ 0.88543411  0.37596773 20.         20.          2.71686971  3.98287384
  0.91699335  3.36370464 20.         20.        ]


## The curse of dimensionality

In this exercise you are going to experience the "curse of dimensionality": namely, data in a high dimensional space becomes increasingly sparse.

We are going to visualize it graphically by plotting 10 random points in unit hypercubes of increasing dimensions (1, 2, 3).

1) To begin with, let us create a random vector of 10 data points uniformly distributed in the interval [0, 1). Plot this distribution using `matplotlib` see method `plt.scatter`.
In order to scatter points, you need 2-dimensional points (axes $x,y$). In this case, just set the $y$ axis value to 0.

In [13]:
import matplotlib.pyplot as plt

In [14]:
## 1: Create 10 points in 1 dimension, and plot them on a line.

data1d = None  # Make sure its shape is (10, 1)


2) Then, do the same for a 2-dimensional space: create 10 random points in the 2-dimensional unit hypercube (a square), and plot them.

In [15]:
## 2: Create 10 points in 2 dimensions, and plot them in the 2D plane.

data2d = None  # Make sure its shape is (10, 2)

What do you notice? Do you think points are more spread out in the 2-dimensional or in the 1-dimensional hypercube?

3) Let us try also with the 3-dimensional space: create 10 random points in the 3-dimensional unit hypercube (a cube), and plot them using [`ax.scatter3D`](https://www.geeksforgeeks.org/3d-scatter-plotting-in-python-using-matplotlib/).

In [16]:
## 3: Create 10 points in 3D, and plot them in the 3D plane.

data3d = None  # Make sure its shape is (10, 3)

What do you notice? Do you think points are more spread out in the 3-dimensional, 2-dimensional or 1-dimensional hypercube?

Let us try to quantify numerically how distant from each other the points in the three hypercubes are. 

(*) Write a function that, taken a list of 10 $k$-dimensional points (shape (10, $k$), for any $k\in\mathbb{N}$), computes the average pairwise distance between all pairs of points.  

The distance between two $k$-dimensional points $x, y$ is given by the formula $dist(x, y) = \sqrt{\sum_{i=1}^k (x_i - y_i)^2}$, for $x,y\in\mathbb{R}^k$.

The average pairwise distance of a list $v$ of 10 $k$-dimensional points is given by the formula: $\frac{\sum_{i=1}^{9} \sum_{j=i+1}^{10} dist(v_i, v_j)}{10 \choose 2}$. Notice that $v$ has shape (10, $k$), and $v_i, v_j$ have both shape $k$. 

The binomial coefficient ${10 \choose 2} := \frac{10!}{2! (10-2)!}$, and it is nothing but the number of distinct pairs you can make with 10 numbers. You can also write it as: ${10 \choose 2} = \sum_{i=1}^{9} \sum_{j=i+1}^{10} 1$.

Try to use numpy core functions and broadcasting when possible.

In [17]:
def dist(x: np.array, y: np.array) -> float:
    return 0.0


def avg_pairwise_distance(v: np.array) -> float:
    return 0.0

Use the above function to compute the average distance between points in `data1d`, between points in `data2d` and between points in `data3d`. Which one is larger?

In [18]:
print(avg_pairwise_distance(data1d))
print(avg_pairwise_distance(data2d))
print(avg_pairwise_distance(data3d))

0.0
0.0
0.0
